// Code generated by pigeon; DO NOT EDIT.

package query

// part of the initializer code block omitted for brevity
import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

func toString(label interface{}) string {
	var sb strings.Builder
	value, ok := label.([]interface{})
	if ok {
		for _, i := range value {
			if i == nil {
				continue
			}
			switch b := i.(type) {
			case []byte:
				sb.WriteByte(b[0])
			case []interface{}:
				s := toString(i)
				sb.WriteString(s)
			default:
				fmt.Printf("error: %T %+v\n", i, i)
			}
		}
	}
	intVs, ok := label.([]uint8)
	if ok {
		for _, i := range intVs {
			sb.WriteString(string(i))
		}
	}
	return sb.String()
}

func toPrimitive(label interface{}) interface{} {
	s := toString(label)
	f, err := strconv.ParseFloat(s, 64)
	if err == nil {
		return f
	}
	i, err := strconv.Atoi(s)
	if err == nil {
		return i
	}
	return s
}

var (
	sorting []string = make([]string, 0)
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 57, col: 1, offset: 1181},
			expr: &actionExpr{
				pos: position{line: 57, col: 15, offset: 1195},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 57, col: 15, offset: 1195},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 57, col: 15, offset: 1195},
							expr: &ruleRefExpr{
								pos:  position{line: 57, col: 15, offset: 1195},
								name: "_",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 57, col: 18, offset: 1198},
							name: "Query",
						},
						&zeroOrOneExpr{
							pos: position{line: 57, col: 24, offset: 1204},
							expr: &ruleRefExpr{
								pos:  position{line: 57, col: 24, offset: 1204},
								name: "_",
							},
						},
						&notExpr{
							pos: position{line: 57, col: 27, offset: 1207},
							expr: &anyMatcher{
								line: 57, col: 28, offset: 1208,
							},
						},
					},
				},
			},
		},
		{
			name: "Query",
			pos:  position{line: 61, col: 1, offset: 1245},
			expr: &ruleRefExpr{
				pos:  position{line: 61, col: 15, offset: 1259},
				name: "Exprs",
			},
		},
		{
			name: "Exprs",
			pos:  position{line: 62, col: 1, offset: 1266},
			expr: &seqExpr{
				pos: position{line: 62, col: 15, offset: 1280},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 62, col: 15, offset: 1280},
						name: "Expr",
					},
					&zeroOrMoreExpr{
						pos: position{line: 62, col: 20, offset: 1285},
						expr: &seqExpr{
							pos: position{line: 62, col: 21, offset: 1286},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 62, col: 21, offset: 1286},
									name: "_",
								},
								&ruleRefExpr{
									pos:  position{line: 62, col: 23, offset: 1288},
									name: "Operator",
								},
								&ruleRefExpr{
									pos:  position{line: 62, col: 32, offset: 1297},
									name: "_",
								},
								&ruleRefExpr{
									pos:  position{line: 62, col: 34, offset: 1299},
									name: "Expr",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Operator",
			pos:  position{line: 63, col: 1, offset: 1307},
			expr: &choiceExpr{
				pos: position{line: 63, col: 15, offset: 1321},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 63, col: 15, offset: 1321},
						run: (*parser).callonOperator2,
						expr: &ruleRefExpr{
							pos:  position{line: 63, col: 15, offset: 1321},
							name: "OR",
						},
					},
					&actionExpr{
						pos: position{line: 63, col: 205, offset: 1511},
						run: (*parser).callonOperator4,
						expr: &ruleRefExpr{
							pos:  position{line: 63, col: 205, offset: 1511},
							name: "AND",
						},
					},
				},
			},
		},
		{
			name: "Expr",
			pos:  position{line: 64, col: 1, offset: 1700},
			expr: &choiceExpr{
				pos: position{line: 64, col: 15, offset: 1714},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 64, col: 15, offset: 1714},
						name: "GroupOrNot",
					},
					&ruleRefExpr{
						pos:  position{line: 64, col: 28, offset: 1727},
						name: "Term",
					},
				},
			},
		},
		{
			name: "Term",
			pos:  position{line: 66, col: 1, offset: 1735},
			expr: &seqExpr{
				pos: position{line: 66, col: 15, offset: 1749},
				exprs: []interface{}{
					&zeroOrOneExpr{
						pos: position{line: 66, col: 15, offset: 1749},
						expr: &ruleRefExpr{
							pos:  position{line: 66, col: 15, offset: 1749},
							name: "NotCheck",
						},
					},
					&choiceExpr{
						pos: position{line: 66, col: 26, offset: 1760},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 66, col: 26, offset: 1760},
								name: "KeyValue",
							},
							&ruleRefExpr{
								pos:  position{line: 66, col: 37, offset: 1771},
								name: "SingleValue",
							},
						},
					},
				},
			},
		},
		{
			name: "NotCheck",
			pos:  position{line: 67, col: 1, offset: 1785},
			expr: &actionExpr{
				pos: position{line: 67, col: 15, offset: 1799},
				run: (*parser).callonNotCheck1,
				expr: &seqExpr{
					pos: position{line: 67, col: 15, offset: 1799},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 67, col: 15, offset: 1799},
							name: "NOT",
						},
						&zeroOrOneExpr{
							pos: position{line: 67, col: 19, offset: 1803},
							expr: &ruleRefExpr{
								pos:  position{line: 67, col: 19, offset: 1803},
								name: "_",
							},
						},
					},
				},
			},
		},
		{
			name: "GroupOrNot",
			pos:  position{line: 72, col: 1, offset: 1876},
			expr: &seqExpr{
				pos: position{line: 72, col: 18, offset: 1893},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 72, col: 18, offset: 1893},
						name: "GroupPrefix",
					},
					&ruleRefExpr{
						pos:  position{line: 72, col: 30, offset: 1905},
						name: "GroupSuffix",
					},
				},
			},
		},
		{
			name: "GroupPrefix",
			pos:  position{line: 73, col: 1, offset: 1918},
			expr: &choiceExpr{
				pos: position{line: 73, col: 18, offset: 1935},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 73, col: 18, offset: 1935},
						name: "NotGroupStart",
					},
					&ruleRefExpr{
						pos:  position{line: 73, col: 34, offset: 1951},
						name: "GroupStart",
					},
				},
			},
		},
		{
			name: "GroupStart",
			pos:  position{line: 74, col: 1, offset: 1963},
			expr: &actionExpr{
				pos: position{line: 74, col: 18, offset: 1980},
				run: (*parser).callonGroupStart1,
				expr: &seqExpr{
					pos: position{line: 74, col: 18, offset: 1980},
					exprs: []interface{}{
						&notExpr{
							pos: position{line: 74, col: 18, offset: 1980},
							expr: &ruleRefExpr{
								pos:  position{line: 74, col: 19, offset: 1981},
								name: "Not",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 74, col: 23, offset: 1985},
							name: "OPENPAREN",
						},
					},
				},
			},
		},
		{
			name: "NotGroupStart",
			pos:  position{line: 75, col: 1, offset: 2033},
			expr: &actionExpr{
				pos: position{line: 75, col: 18, offset: 2050},
				run: (*parser).callonNotGroupStart1,
				expr: &seqExpr{
					pos: position{line: 75, col: 18, offset: 2050},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 75, col: 18, offset: 2050},
							name: "Not",
						},
						&ruleRefExpr{
							pos:  position{line: 75, col: 22, offset: 2054},
							name: "OPENPAREN",
						},
					},
				},
			},
		},
		{
			name: "GroupSuffix",
			pos:  position{line: 76, col: 1, offset: 2099},
			expr: &seqExpr{
				pos: position{line: 76, col: 18, offset: 2116},
				exprs: []interface{}{
					&zeroOrOneExpr{
						pos: position{line: 76, col: 18, offset: 2116},
						expr: &ruleRefExpr{
							pos:  position{line: 76, col: 18, offset: 2116},
							name: "_",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 76, col: 21, offset: 2119},
						name: "Query",
					},
					&zeroOrOneExpr{
						pos: position{line: 76, col: 27, offset: 2125},
						expr: &ruleRefExpr{
							pos:  position{line: 76, col: 27, offset: 2125},
							name: "_",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 76, col: 30, offset: 2128},
						name: "CLOSEPAREN",
					},
				},
			},
		},
		{
			name: "Not",
			pos:  position{line: 77, col: 1, offset: 2140},
			expr: &seqExpr{
				pos: position{line: 77, col: 18, offset: 2157},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 77, col: 18, offset: 2157},
						name: "NOT",
					},
					&zeroOrOneExpr{
						pos: position{line: 77, col: 22, offset: 2161},
						expr: &ruleRefExpr{
							pos:  position{line: 77, col: 22, offset: 2161},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "KeyValue",
			pos:  position{line: 79, col: 1, offset: 2167},
			expr: &actionExpr{
				pos: position{line: 79, col: 18, offset: 2184},
				run: (*parser).callonKeyValue1,
				expr: &seqExpr{
					pos: position{line: 79, col: 18, offset: 2184},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 79, col: 18, offset: 2184},
							label: "k",
							expr: &ruleRefExpr{
								pos:  position{line: 79, col: 20, offset: 2186},
								name: "Key",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 79, col: 24, offset: 2190},
							name: "COLON",
						},
						&labeledExpr{
							pos:   position{line: 79, col: 30, offset: 2196},
							label: "v",
							expr: &ruleRefExpr{
								pos:  position{line: 79, col: 32, offset: 2198},
								name: "Value",
							},
						},
					},
				},
			},
		},
		{
			name: "SingleValue",
			pos:  position{line: 85, col: 1, offset: 2307},
			expr: &choiceExpr{
				pos: position{line: 85, col: 18, offset: 2324},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 85, col: 18, offset: 2324},
						name: "Phrase",
					},
					&ruleRefExpr{
						pos:  position{line: 85, col: 27, offset: 2333},
						name: "DateTime",
					},
					&ruleRefExpr{
						pos:  position{line: 85, col: 38, offset: 2344},
						name: "Number",
					},
					&ruleRefExpr{
						pos:  position{line: 85, col: 47, offset: 2353},
						name: "Word",
					},
				},
			},
		},
		{
			name: "Key",
			pos:  position{line: 86, col: 1, offset: 2359},
			expr: &actionExpr{
				pos: position{line: 86, col: 18, offset: 2376},
				run: (*parser).callonKey1,
				expr: &oneOrMoreExpr{
					pos: position{line: 86, col: 18, offset: 2376},
					expr: &charClassMatcher{
						pos:        position{line: 86, col: 18, offset: 2376},
						val:        "[A-Za-z0-9_-]",
						chars:      []rune{'_', '-'},
						ranges:     []rune{'A', 'Z', 'a', 'z', '0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 87, col: 1, offset: 2423},
			expr: &choiceExpr{
				pos: position{line: 87, col: 18, offset: 2440},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 87, col: 18, offset: 2440},
						name: "Window",
					},
					&ruleRefExpr{
						pos:  position{line: 87, col: 27, offset: 2449},
						name: "OpValue",
					},
					&ruleRefExpr{
						pos:  position{line: 87, col: 37, offset: 2459},
						name: "Phrase",
					},
					&ruleRefExpr{
						pos:  position{line: 87, col: 46, offset: 2468},
						name: "DateTime",
					},
					&ruleRefExpr{
						pos:  position{line: 87, col: 57, offset: 2479},
						name: "Number",
					},
					&actionExpr{
						pos: position{line: 87, col: 66, offset: 2488},
						run: (*parser).callonValue7,
						expr: &labeledExpr{
							pos:   position{line: 87, col: 66, offset: 2488},
							label: "w",
							expr: &ruleRefExpr{
								pos:  position{line: 87, col: 68, offset: 2490},
								name: "Word",
							},
						},
					},
				},
			},
		},
		{
			name: "OpValue",
			pos:  position{line: 90, col: 1, offset: 2562},
			expr: &choiceExpr{
				pos: position{line: 90, col: 17, offset: 2578},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 90, col: 17, offset: 2578},
						run: (*parser).callonOpValue2,
						expr: &seqExpr{
							pos: position{line: 90, col: 17, offset: 2578},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 90, col: 17, offset: 2578},
									name: "FIELDOP",
								},
								&labeledExpr{
									pos:   position{line: 90, col: 25, offset: 2586},
									label: "d",
									expr: &ruleRefExpr{
										pos:  position{line: 90, col: 27, offset: 2588},
										name: "DateTime",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 90, col: 54, offset: 2615},
						run: (*parser).callonOpValue7,
						expr: &seqExpr{
							pos: position{line: 90, col: 54, offset: 2615},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 90, col: 54, offset: 2615},
									name: "FIELDOP",
								},
								&labeledExpr{
									pos:   position{line: 90, col: 62, offset: 2623},
									label: "n",
									expr: &ruleRefExpr{
										pos:  position{line: 90, col: 64, offset: 2625},
										name: "Number",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 90, col: 89, offset: 2650},
						run: (*parser).callonOpValue12,
						expr: &seqExpr{
							pos: position{line: 90, col: 89, offset: 2650},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 90, col: 89, offset: 2650},
									name: "FIELDOP",
								},
								&labeledExpr{
									pos:   position{line: 90, col: 97, offset: 2658},
									label: "p",
									expr: &ruleRefExpr{
										pos:  position{line: 90, col: 99, offset: 2660},
										name: "Phrase",
									},
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 90, col: 125, offset: 2686},
						run: (*parser).callonOpValue17,
						expr: &seqExpr{
							pos: position{line: 90, col: 125, offset: 2686},
							exprs: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 90, col: 125, offset: 2686},
									name: "FIELDOP",
								},
								&labeledExpr{
									pos:   position{line: 90, col: 133, offset: 2694},
									label: "w",
									expr: &ruleRefExpr{
										pos:  position{line: 90, col: 135, offset: 2696},
										name: "Word",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DateTime",
			pos:  position{line: 91, col: 1, offset: 2719},
			expr: &actionExpr{
				pos: position{line: 91, col: 17, offset: 2735},
				run: (*parser).callonDateTime1,
				expr: &seqExpr{
					pos: position{line: 91, col: 17, offset: 2735},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 91, col: 17, offset: 2735},
							name: "Date",
						},
						&ruleRefExpr{
							pos:  position{line: 91, col: 22, offset: 2740},
							name: "TEE",
						},
						&ruleRefExpr{
							pos:  position{line: 91, col: 26, offset: 2744},
							name: "Time",
						},
						&ruleRefExpr{
							pos:  position{line: 91, col: 31, offset: 2749},
							name: "ZEE",
						},
					},
				},
			},
		},
		{
			name: "Phrase",
			pos:  position{line: 94, col: 1, offset: 2848},
			expr: &actionExpr{
				pos: position{line: 94, col: 17, offset: 2864},
				run: (*parser).callonPhrase1,
				expr: &seqExpr{
					pos: position{line: 94, col: 17, offset: 2864},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 94, col: 17, offset: 2864},
							name: "DQ",
						},
						&oneOrMoreExpr{
							pos: position{line: 94, col: 20, offset: 2867},
							expr: &charClassMatcher{
								pos:        position{line: 94, col: 20, offset: 2867},
								val:        "[^\"]",
								chars:      []rune{'"'},
								ignoreCase: false,
								inverted:   true,
							},
						},
						&ruleRefExpr{
							pos:  position{line: 94, col: 26, offset: 2873},
							name: "DQ",
						},
					},
				},
			},
		},
		{
			name: "Window",
			pos:  position{line: 97, col: 1, offset: 2986},
			expr: &actionExpr{
				pos: position{line: 97, col: 17, offset: 3002},
				run: (*parser).callonWindow1,
				expr: &seqExpr{
					pos: position{line: 97, col: 17, offset: 3002},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 97, col: 17, offset: 3002},
							name: "OPENBRACKET",
						},
						&zeroOrOneExpr{
							pos: position{line: 97, col: 29, offset: 3014},
							expr: &ruleRefExpr{
								pos:  position{line: 97, col: 29, offset: 3014},
								name: "_",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 97, col: 32, offset: 3017},
							name: "WindowRange",
						},
						&zeroOrOneExpr{
							pos: position{line: 97, col: 44, offset: 3029},
							expr: &ruleRefExpr{
								pos:  position{line: 97, col: 44, offset: 3029},
								name: "_",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 97, col: 47, offset: 3032},
							name: "CLOSEBRACKET",
						},
					},
				},
			},
		},
		{
			name: "WindowRange",
			pos:  position{line: 98, col: 1, offset: 3078},
			expr: &choiceExpr{
				pos: position{line: 98, col: 17, offset: 3094},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 98, col: 17, offset: 3094},
						name: "DateWindow",
					},
					&ruleRefExpr{
						pos:  position{line: 98, col: 30, offset: 3107},
						name: "NumberWindow",
					},
				},
			},
		},
		{
			name: "DateWindow",
			pos:  position{line: 99, col: 1, offset: 3121},
			expr: &seqExpr{
				pos: position{line: 99, col: 17, offset: 3137},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 99, col: 17, offset: 3137},
						name: "WinDateTime",
					},
					&ruleRefExpr{
						pos:  position{line: 99, col: 29, offset: 3149},
						name: "TILDA",
					},
					&ruleRefExpr{
						pos:  position{line: 99, col: 35, offset: 3155},
						name: "WinDateTime",
					},
				},
			},
		},
		{
			name: "WinDateTime",
			pos:  position{line: 100, col: 1, offset: 3168},
			expr: &seqExpr{
				pos: position{line: 100, col: 17, offset: 3184},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 100, col: 17, offset: 3184},
						name: "Date",
					},
					&ruleRefExpr{
						pos:  position{line: 100, col: 22, offset: 3189},
						name: "TEE",
					},
					&ruleRefExpr{
						pos:  position{line: 100, col: 26, offset: 3193},
						name: "Time",
					},
					&ruleRefExpr{
						pos:  position{line: 100, col: 31, offset: 3198},
						name: "ZEE",
					},
				},
			},
		},
		{
			name: "NumberWindow",
			pos:  position{line: 101, col: 1, offset: 3203},
			expr: &seqExpr{
				pos: position{line: 101, col: 17, offset: 3219},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 101, col: 17, offset: 3219},
						name: "WinNumber",
					},
					&ruleRefExpr{
						pos:  position{line: 101, col: 27, offset: 3229},
						name: "TILDA",
					},
					&zeroOrOneExpr{
						pos: position{line: 101, col: 33, offset: 3235},
						expr: &ruleRefExpr{
							pos:  position{line: 101, col: 33, offset: 3235},
							name: "DASH",
						},
					},
					&ruleRefExpr{
						pos:  position{line: 101, col: 39, offset: 3241},
						name: "WinNumber",
					},
				},
			},
		},
		{
			name: "WinNumber",
			pos:  position{line: 102, col: 1, offset: 3252},
			expr: &seqExpr{
				pos: position{line: 102, col: 17, offset: 3268},
				exprs: []interface{}{
					&choiceExpr{
						pos: position{line: 102, col: 18, offset: 3269},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 102, col: 18, offset: 3269},
								name: "DIGIT",
							},
							&ruleRefExpr{
								pos:  position{line: 102, col: 26, offset: 3277},
								name: "DOT",
							},
							&ruleRefExpr{
								pos:  position{line: 102, col: 31, offset: 3282},
								name: "DASH",
							},
						},
					},
					&zeroOrMoreExpr{
						pos: position{line: 102, col: 37, offset: 3288},
						expr: &choiceExpr{
							pos: position{line: 102, col: 38, offset: 3289},
							alternatives: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 102, col: 38, offset: 3289},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 102, col: 46, offset: 3297},
									name: "DASH",
								},
								&ruleRefExpr{
									pos:  position{line: 102, col: 53, offset: 3304},
									name: "EEE",
								},
								&ruleRefExpr{
									pos:  position{line: 102, col: 59, offset: 3310},
									name: "DOT",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Date",
			pos:  position{line: 106, col: 1, offset: 3340},
			expr: &seqExpr{
				pos: position{line: 106, col: 12, offset: 3351},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 106, col: 12, offset: 3351},
						name: "Digits4",
					},
					&ruleRefExpr{
						pos:  position{line: 106, col: 20, offset: 3359},
						name: "DASH",
					},
					&ruleRefExpr{
						pos:  position{line: 106, col: 25, offset: 3364},
						name: "Digits2",
					},
					&ruleRefExpr{
						pos:  position{line: 106, col: 33, offset: 3372},
						name: "DASH",
					},
					&ruleRefExpr{
						pos:  position{line: 106, col: 38, offset: 3377},
						name: "Digits2",
					},
				},
			},
		},
		{
			name: "Time",
			pos:  position{line: 107, col: 1, offset: 3386},
			expr: &seqExpr{
				pos: position{line: 107, col: 12, offset: 3397},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 107, col: 12, offset: 3397},
						name: "Digits2",
					},
					&ruleRefExpr{
						pos:  position{line: 107, col: 20, offset: 3405},
						name: "COLON",
					},
					&ruleRefExpr{
						pos:  position{line: 107, col: 26, offset: 3411},
						name: "Digits2",
					},
					&ruleRefExpr{
						pos:  position{line: 107, col: 34, offset: 3419},
						name: "COLON",
					},
					&ruleRefExpr{
						pos:  position{line: 107, col: 40, offset: 3425},
						name: "Digits2",
					},
				},
			},
		},
		{
			name: "Word",
			pos:  position{line: 108, col: 1, offset: 3434},
			expr: &actionExpr{
				pos: position{line: 108, col: 12, offset: 3445},
				run: (*parser).callonWord1,
				expr: &seqExpr{
					pos: position{line: 108, col: 12, offset: 3445},
					exprs: []interface{}{
						&charClassMatcher{
							pos:        position{line: 108, col: 12, offset: 3445},
							val:        "[a-zA-Z_]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 108, col: 22, offset: 3455},
							expr: &charClassMatcher{
								pos:        position{line: 108, col: 22, offset: 3455},
								val:        "[a-zA-Z0-9_]",
								chars:      []rune{'_'},
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 109, col: 1, offset: 3525},
			expr: &actionExpr{
				pos: position{line: 109, col: 12, offset: 3536},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 109, col: 12, offset: 3536},
					exprs: []interface{}{
						&choiceExpr{
							pos: position{line: 109, col: 13, offset: 3537},
							alternatives: []interface{}{
								&ruleRefExpr{
									pos:  position{line: 109, col: 13, offset: 3537},
									name: "DIGIT",
								},
								&ruleRefExpr{
									pos:  position{line: 109, col: 21, offset: 3545},
									name: "DOT",
								},
								&ruleRefExpr{
									pos:  position{line: 109, col: 26, offset: 3550},
									name: "DASH",
								},
							},
						},
						&zeroOrMoreExpr{
							pos: position{line: 109, col: 32, offset: 3556},
							expr: &choiceExpr{
								pos: position{line: 109, col: 33, offset: 3557},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 109, col: 33, offset: 3557},
										name: "DIGIT",
									},
									&ruleRefExpr{
										pos:  position{line: 109, col: 41, offset: 3565},
										name: "DASH",
									},
									&ruleRefExpr{
										pos:  position{line: 109, col: 48, offset: 3572},
										name: "EEE",
									},
									&ruleRefExpr{
										pos:  position{line: 109, col: 54, offset: 3578},
										name: "DOT",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Digits2",
			pos:  position{line: 110, col: 1, offset: 3616},
			expr: &seqExpr{
				pos: position{line: 110, col: 12, offset: 3627},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 110, col: 12, offset: 3627},
						name: "DIGIT",
					},
					&ruleRefExpr{
						pos:  position{line: 110, col: 18, offset: 3633},
						name: "DIGIT",
					},
				},
			},
		},
		{
			name: "Digits4",
			pos:  position{line: 111, col: 1, offset: 3640},
			expr: &seqExpr{
				pos: position{line: 111, col: 12, offset: 3651},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 111, col: 12, offset: 3651},
						name: "Digits2",
					},
					&ruleRefExpr{
						pos:  position{line: 111, col: 20, offset: 3659},
						name: "Digits2",
					},
				},
			},
		},
		{
			name: "OPENPAREN",
			pos:  position{line: 113, col: 1, offset: 3670},
			expr: &litMatcher{
				pos:        position{line: 113, col: 17, offset: 3686},
				val:        "(",
				ignoreCase: false,
				want:       "\"(\"",
			},
		},
		{
			name: "CLOSEPAREN",
			pos:  position{line: 114, col: 1, offset: 3691},
			expr: &litMatcher{
				pos:        position{line: 114, col: 17, offset: 3707},
				val:        ")",
				ignoreCase: false,
				want:       "\")\"",
			},
		},
		{
			name: "OPENBRACKET",
			pos:  position{line: 115, col: 1, offset: 3712},
			expr: &litMatcher{
				pos:        position{line: 115, col: 17, offset: 3728},
				val:        "[",
				ignoreCase: false,
				want:       "\"[\"",
			},
		},
		{
			name: "CLOSEBRACKET",
			pos:  position{line: 116, col: 1, offset: 3733},
			expr: &litMatcher{
				pos:        position{line: 116, col: 17, offset: 3749},
				val:        "]",
				ignoreCase: false,
				want:       "\"]\"",
			},
		},
		{
			name: "DIGIT",
			pos:  position{line: 118, col: 1, offset: 3756},
			expr: &charClassMatcher{
				pos:        position{line: 118, col: 12, offset: 3767},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "DASH",
			pos:  position{line: 119, col: 1, offset: 3774},
			expr: &litMatcher{
				pos:        position{line: 119, col: 12, offset: 3785},
				val:        "-",
				ignoreCase: false,
				want:       "\"-\"",
			},
		},
		{
			name: "COLON",
			pos:  position{line: 120, col: 1, offset: 3790},
			expr: &litMatcher{
				pos:        position{line: 120, col: 12, offset: 3801},
				val:        ":",
				ignoreCase: false,
				want:       "\":\"",
			},
		},
		{
			name: "TILDA",
			pos:  position{line: 121, col: 1, offset: 3806},
			expr: &litMatcher{
				pos:        position{line: 121, col: 12, offset: 3817},
				val:        "~",
				ignoreCase: false,
				want:       "\"~\"",
			},
		},
		{
			name: "DQ",
			pos:  position{line: 122, col: 1, offset: 3822},
			expr: &litMatcher{
				pos:        position{line: 122, col: 12, offset: 3833},
				val:        "\"",
				ignoreCase: false,
				want:       "\"\\\"\"",
			},
		},
		{
			name: "TEE",
			pos:  position{line: 123, col: 1, offset: 3838},
			expr: &litMatcher{
				pos:        position{line: 123, col: 12, offset: 3849},
				val:        "T",
				ignoreCase: false,
				want:       "\"T\"",
			},
		},
		{
			name: "ZEE",
			pos:  position{line: 124, col: 1, offset: 3854},
			expr: &litMatcher{
				pos:        position{line: 124, col: 12, offset: 3865},
				val:        "Z",
				ignoreCase: false,
				want:       "\"Z\"",
			},
		},
		{
			name: "EEE",
			pos:  position{line: 125, col: 1, offset: 3870},
			expr: &charClassMatcher{
				pos:        position{line: 125, col: 12, offset: 3881},
				val:        "[eE]",
				chars:      []rune{'e', 'E'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "DOT",
			pos:  position{line: 126, col: 1, offset: 3887},
			expr: &litMatcher{
				pos:        position{line: 126, col: 12, offset: 3898},
				val:        ".",
				ignoreCase: false,
				want:       "\".\"",
			},
		},
		{
			name: "NOT",
			pos:  position{line: 128, col: 1, offset: 3905},
			expr: &choiceExpr{
				pos: position{line: 128, col: 12, offset: 3916},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 128, col: 12, offset: 3916},
						val:        "NOT",
						ignoreCase: false,
						want:       "\"NOT\"",
					},
					&litMatcher{
						pos:        position{line: 128, col: 20, offset: 3924},
						val:        "!",
						ignoreCase: false,
						want:       "\"!\"",
					},
				},
			},
		},
		{
			name: "AND",
			pos:  position{line: 130, col: 1, offset: 3931},
			expr: &choiceExpr{
				pos: position{line: 130, col: 12, offset: 3942},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 130, col: 12, offset: 3942},
						val:        "AND",
						ignoreCase: false,
						want:       "\"AND\"",
					},
					&litMatcher{
						pos:        position{line: 130, col: 20, offset: 3950},
						val:        "&",
						ignoreCase: false,
						want:       "\"&\"",
					},
				},
			},
		},
		{
			name: "OR",
			pos:  position{line: 131, col: 1, offset: 3955},
			expr: &choiceExpr{
				pos: position{line: 131, col: 12, offset: 3966},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 131, col: 12, offset: 3966},
						val:        "OR",
						ignoreCase: false,
						want:       "\"OR\"",
					},
					&litMatcher{
						pos:        position{line: 131, col: 19, offset: 3973},
						val:        "|",
						ignoreCase: false,
						want:       "\"|\"",
					},
				},
			},
		},
		{
			name: "FIELDOP",
			pos:  position{line: 133, col: 1, offset: 3980},
			expr: &choiceExpr{
				pos: position{line: 133, col: 12, offset: 3991},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 133, col: 12, offset: 3991},
						name: "GTE",
					},
					&ruleRefExpr{
						pos:  position{line: 133, col: 18, offset: 3997},
						name: "LTE",
					},
					&ruleRefExpr{
						pos:  position{line: 133, col: 24, offset: 4003},
						name: "GT",
					},
					&ruleRefExpr{
						pos:  position{line: 133, col: 29, offset: 4008},
						name: "LT",
					},
					&ruleRefExpr{
						pos:  position{line: 133, col: 34, offset: 4013},
						name: "NE",
					},
					&ruleRefExpr{
						pos:  position{line: 133, col: 39, offset: 4018},
						name: "EQ",
					},
				},
			},
		},
		{
			name: "GTE",
			pos:  position{line: 134, col: 1, offset: 4022},
			expr: &actionExpr{
				pos: position{line: 134, col: 12, offset: 4033},
				run: (*parser).callonGTE1,
				expr: &litMatcher{
					pos:        position{line: 134, col: 12, offset: 4033},
					val:        ">=",
					ignoreCase: false,
					want:       "\">=\"",
				},
			},
		},
		{
			name: "LTE",
			pos:  position{line: 135, col: 1, offset: 4112},
			expr: &actionExpr{
				pos: position{line: 135, col: 12, offset: 4123},
				run: (*parser).callonLTE1,
				expr: &litMatcher{
					pos:        position{line: 135, col: 12, offset: 4123},
					val:        "<=",
					ignoreCase: false,
					want:       "\"<=\"",
				},
			},
		},
		{
			name: "GT",
			pos:  position{line: 136, col: 1, offset: 4202},
			expr: &actionExpr{
				pos: position{line: 136, col: 12, offset: 4213},
				run: (*parser).callonGT1,
				expr: &litMatcher{
					pos:        position{line: 136, col: 12, offset: 4213},
					val:        ">",
					ignoreCase: false,
					want:       "\">\"",
				},
			},
		},
		{
			name: "LT",
			pos:  position{line: 137, col: 1, offset: 4292},
			expr: &actionExpr{
				pos: position{line: 137, col: 12, offset: 4303},
				run: (*parser).callonLT1,
				expr: &litMatcher{
					pos:        position{line: 137, col: 12, offset: 4303},
					val:        "<",
					ignoreCase: false,
					want:       "\"<\"",
				},
			},
		},
		{
			name: "NE",
			pos:  position{line: 138, col: 1, offset: 4382},
			expr: &actionExpr{
				pos: position{line: 138, col: 12, offset: 4393},
				run: (*parser).callonNE1,
				expr: &litMatcher{
					pos:        position{line: 138, col: 12, offset: 4393},
					val:        "!=",
					ignoreCase: false,
					want:       "\"!=\"",
				},
			},
		},
		{
			name: "EQ",
			pos:  position{line: 139, col: 1, offset: 4472},
			expr: &actionExpr{
				pos: position{line: 139, col: 12, offset: 4483},
				run: (*parser).callonEQ1,
				expr: &litMatcher{
					pos:        position{line: 139, col: 12, offset: 4483},
					val:        "=",
					ignoreCase: false,
					want:       "\"=\"",
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 141, col: 1, offset: 4564},
			expr: &oneOrMoreExpr{
				pos: position{line: 141, col: 19, offset: 4582},
				expr: &charClassMatcher{
					pos:        position{line: 141, col: 19, offset: 4582},
					val:        "[ \\n\\t\\r]",
					chars:      []rune{' ', '\n', '\t', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
	},
}

func (c *current) onInput1() (interface{}, error) {

	return N.Query(), nil
}

func (p *parser) callonInput1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInput1()
}

func (c *current) onOperator2() (interface{}, error) {
	N.NewCondition()
	if N.CurrentNode().Operator == ANDOP {
		return nil, errors.New("you cant mix AND and OR operator")
	}
	N.CurrentNode().Operator = OROP
	return N.CurrentNode(), nil
}

func (p *parser) callonOperator2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOperator2()
}

func (c *current) onOperator4() (interface{}, error) {
	N.NewCondition()
	if N.CurrentNode().Operator == OROP {
		return nil, errors.New("you cant mix AND and OR operator")
	}
	N.CurrentNode().Operator = ANDOP
	return N.CurrentNode(), nil
}

func (p *parser) callonOperator4() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOperator4()
}

func (c *current) onNotCheck1() (interface{}, error) {

	N.CurrentCondition().Invert = true
	return nil, nil
}

func (p *parser) callonNotCheck1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNotCheck1()
}

func (c *current) onGroupStart1() (interface{}, error) {
	n := N.NewNode()
	return n, nil
}

func (p *parser) callonGroupStart1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGroupStart1()
}

func (c *current) onNotGroupStart1() (interface{}, error) {
	return N.CurrentNode(), nil
}

func (p *parser) callonNotGroupStart1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNotGroupStart1()
}

func (c *current) onKeyValue1(k, v interface{}) (interface{}, error) {

	cd := N.CurrentCondition()
	cd.Field = k.(string)
	cd.Value = v
	return cd, nil
}

func (p *parser) callonKeyValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKeyValue1(stack["k"], stack["v"])
}

func (c *current) onKey1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonKey1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKey1()
}

func (c *current) onValue7(w interface{}) (interface{}, error) {
	return w, nil
}

func (p *parser) callonValue7() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue7(stack["w"])
}

func (c *current) onOpValue2(d interface{}) (interface{}, error) {
	return d, nil
}

func (p *parser) callonOpValue2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOpValue2(stack["d"])
}

func (c *current) onOpValue7(n interface{}) (interface{}, error) {
	return n, nil
}

func (p *parser) callonOpValue7() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOpValue7(stack["n"])
}

func (c *current) onOpValue12(p interface{}) (interface{}, error) {
	return p, nil
}

func (p *parser) callonOpValue12() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOpValue12(stack["p"])
}

func (c *current) onOpValue17(w interface{}) (interface{}, error) {
	return w, nil
}

func (p *parser) callonOpValue17() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onOpValue17(stack["w"])
}

func (c *current) onDateTime1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonDateTime1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDateTime1()
}

func (c *current) onPhrase1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonPhrase1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPhrase1()
}

func (c *current) onWindow1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonWindow1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWindow1()
}

func (c *current) onWord1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonWord1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWord1()
}

func (c *current) onNumber1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onGTE1() (interface{}, error) {
	N.CurrentCondition().Operator = GE
	return N.CurrentCondition(), nil
}

func (p *parser) callonGTE1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGTE1()
}

func (c *current) onLTE1() (interface{}, error) {
	N.CurrentCondition().Operator = LE
	return N.CurrentCondition(), nil
}

func (p *parser) callonLTE1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLTE1()
}

func (c *current) onGT1() (interface{}, error) {
	N.CurrentCondition().Operator = GT
	return N.CurrentCondition(), nil
}

func (p *parser) callonGT1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGT1()
}

func (c *current) onLT1() (interface{}, error) {
	N.CurrentCondition().Operator = LT
	return N.CurrentCondition(), nil
}

func (p *parser) callonLT1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLT1()
}

func (c *current) onNE1() (interface{}, error) {
	N.CurrentCondition().Operator = NE
	return N.CurrentCondition(), nil
}

func (p *parser) callonNE1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNE1()
}

func (c *current) onEQ1() (interface{}, error) {
	N.CurrentCondition().Operator = EQ
	return N.CurrentCondition(), nil
}

func (p *parser) callonEQ1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEQ1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
