engine:
  storage:
    properties:
      accessKey: D9Q2D6JQGW1MVCC98LQL
      secretKey: LDX7QHY/IsNiA9DbdycGMuOP0M4khr0+06DKrFAr
      password: 4jsfhdjHsd?
  index:
    properties:
      username: blobstore
      password: blobstore
      authdatabase: blobstore
      database: blobstore