# port of the http server
port: 8080
# port of the https server
sslport: 8443
# this is the servicURL from outside
serviceURL: https://127.0.0.1:8443
secretfile: ""
apikey: false
healthcheck:
  period: 30
# enable/disable metrics 
metrics:
  enable: false
logging:
  level: info
  filename: ""
  gelf-url:
  gelf-port:
engine:
  retentionManager: SingleRetention
  tenantautoadd: true
  backupsyncmode: false
  storage:
    storageclass: SimpleFile
    properties:
      rootpath: /data/storage
  cache:
    storageclass: FastCache
    properties:
      rootpath: /data/cache
      maxcount: 100000
      maxramusage: 1024000000
  backup:
    storageclass: #S3Storage
    properties:
      endpoint: #"http://127.0.0.1:9002"
      bucket: #"goblobstore"
      accessKey: 
      secretKey: 
      password: 
      insecure: true
headermapping:
  headerprefix: x-
  retention:
  tenant: 
  apikey: 
  filename:
auth:
  type: jwt
  properties: 
    validate: true
    strict: true
    tenantClaim: Tenant
    roleClaim: Roles
    rolemapping: 
        object-reader:
        object-creator:
        object-admin:
        tenant-admin:
        admin:
