secretfile: ""
apikey: false
service:
  http:
    # port of the http server
    port: 8000
    # port of the https server for payload only
    sslport: 8443
    # this is the servicURL from outside
    serviceURL: https://localhost:8443
    # other dns names (used for certificate)
    dnss: 
      - host.docker.internal
      - localhost
    # other ips (used for certificate)
    ips: 
      - 127.0.0.1
  #configure the healthcheck system
  healthcheck:
    # period in seconds to start the healtcheck
    period: 30
    startdelay: 3

# enable/disable metrics 
# enable/disable metrics 
metrics:
  enable: true
logging:
  level: debug
  filename: ""
engine:
  retentionManager: SingleRetention
  tenantautoadd: true
  backupsyncmode: false
  allowtntbackup: true
  storage:
    storageclass: sfmv
    properties:
      rootpath: H:/temp/blbmv
      tenantpath: H:/temp/blbstg/tnt
  cache:
    storageclass: FastCache
    properties:
      rootpath: H:/temp/blbcache
      maxcount: 100000
      maxramusage: 1024000000
headermapping:
  headerprefix: x-
  retention:
  tenant: 
  apikey: 
  filename:
#  apikey: X-es-apikey
auth:
  type: #jwt
  properties: 
    validate: false
    strict: true
    tenantClaim: Tenant
    roleClaim: 
    rolemapping: 
        object-reader: Reader
        object-creator: Creator
        object-admin: ObAdmin
        tenant-admin: TnAdmin
        admin: Admin
