secretfile: "configs/secret.yaml"
apikey: false
service:
  http:
    # port of the http server
    port: 8000
    # port of the https server for payload only
    sslport: 8443
    # this is the servicURL from outside
    serviceURL: https://localhost:8443
    # other dns names (used for certificate)
    dnss: 
      - host.docker.internal
      - localhost
    # other ips (used for certificate)
    ips: 
      - 127.0.0.1
  #configure the healthcheck system
  healthcheck:
    # period in seconds to start the healtcheck
    period: 30
    startdelay: 3

# enable/disable metrics 
metrics:
  enable: false
logging:
  level: info
  filename: ""
engine:
  retentionManager: SingleRetention
  tenantautoadd: true
  backupsyncmode: false
  storage:
    storageclass: S3Storage
    properties:
      endpoint: "http://127.0.0.1:9002"
      bucket: "goblobstore"
      insecure: true
      accessKey: 
      secretKey: 
      password: 
headermapping:
  headerprefix: X-
  retention: X-es-retention
  tenant: X-es-tenant
  apikey: X-es-apikey
  filename: X-es-filename

#  apikey: X-es-apikey
