port: 8000
sslport: 8444
serviceURL: https://127.0.0.1:8444
secretfile: ""
healthcheck:
  period: 30
logging:
  level: debug
  filename: ""
storage:
  storageclass: SimpleFile
  rootpath: h:/temp/blobstorage
