port: 8000
sslport: 8443
serviceURL: https://127.0.0.1:8443
secretfile: ""
healthcheck:
  period: 30
logging:
  level: debug
  filename: ""
storage:
  storageclass: SimpleFile
  rootpath: ./testdata/blobstorage
  retentionManager: SingleRetention
  
headermapping:
  headerprefix: x-
  retention: X-es-retention
  tenant: X-es-tenant
  apikey: 
#  apikey: X-es-apikey
