port: 8000
sslport: 8443
serviceURL: https://127.0.0.1:8443
secretfile: ""
healthcheck:
  period: 30
logging:
  level: debug
  filename: ""
storage:
  storageclass: SimpleFile
  rootpath: h:/temp/blobstorage
headermapping:
  retention: X-es-retention
  tenant: X-es-tenant
  apikey: X-es-apikey
