port: 8000
sslport: 8443
serviceURL: https://127.0.0.1:8443
secretfile: "configs/secret.yaml"
apikey: false
healthcheck:
  period: 30
metrics:
  enable: true
logging:
  level: debug
  filename: "${logfile}"
engine:
  retentionManager: SingleRetention
  tenantautoadd: true
  backupsyncmode: false
  storage:
    storageclass: SimpleFile
    properties:
      rootpath: R:/blbstg
  cache:
    storageclass: FastCache
    properties:
      rootpath: R:/blbcache
      maxcount: 100000
      maxramusage: 1024000000
  index:
    storageclass: MongoDB
    properties:
      hosts: 
        - 127.0.0.1:27017
      username:
      password:
      authdatabase: blobstore
      database: blobstore
headermapping:
  headerprefix: x-
  retention:
  tenant: 
  apikey: 
  filename:
auth:
  type: jwt
  properties: 
    validate: true
    strict: true
    tenantClaim: Tenant
    roleClaim: 
    rolemapping: 
        object-reader: Reader
        object-creator: Creator
        object-admin: ObAdmin
        tenant-admin: TnAdmin
        admin: Admin
