port: 8000
sslport: 8443
serviceURL: https://127.0.0.1:8443
secretfile: ""
apikey: false
healthcheck:
  period: 30
# enable/disable metrics 
metrics:
  enable: true
logging:
  level: debug
  filename: ""
engine:
  retentionManager: SingleRetention
  tenantautoadd: true
  backupsyncmode: false
  storage:
    storageclass: SimpleFile
    properties:
      rootpath: E:/blb_bck
headermapping:
  headerprefix: x-
  retention:
  tenant: 
  apikey: 
  filename:
#  apikey: X-es-apikey
auth:
  type: #jwt
  properties: 
    validate: false
    strict: true
    tenantClaim: Tenant
    roleClaim: 
    rolemapping: 
        object-reader: Reader
        object-creator: Creator
        object-admin: ObAdmin
        tenant-admin: TnAdmin
        admin: Admin
