secretfile: ""
apikey: false
service:
  http:
    # port of the http server
    port: 8080
    # port of the https server for payload only
    sslport: 8453
    # this is the servicURL from outside
    serviceURL: https://localhost:8443
    # other dns names (used for certificate)
    dnss: 
      - host.docker.internal
      - localhost
    # other ips (used for certificate)
    ips: 
      - 127.0.0.1
  #configure the healthcheck system
  healthcheck:
    # period in seconds to start the healtcheck
    period: 30
    startdelay: 3

# enable/disable metrics 
metrics:
  enable: false
logging:
  level: debug
  filename: ""
engine:
  retentionManager: SingleRetention
  tenantautoadd: true
  backupsyncmode: false
  allowtntbackup: true
  storage:
    storageclass: SimpleFile
    properties:
      rootpath: H:/temp/blbstg
  backup:
    storageclass: S3Storage
    properties:
      endpoint: "https://127.0.0.1:9002"
      bucket: "goblobstore"
      accessKey: D9Q2D6JQGW1MVCC98LQL
      secretKey: LDX7QHY/IsNiA9DbdycGMuOP0M4khr0+06DKrFAr
      password: 4jsfhdjHsd?
      insecure: false
headermapping:
  headerprefix: x-
  retention: X-es-retention
  tenant: X-es-tenant
  apikey: 
  filename: X-es-filename
#  apikey: X-es-apikey
