port: 8000
sslport: 8443
serviceURL: https://127.0.0.1:8443
secretfile: ""
healthcheck:
  period: 30
logging:
  level: debug
  filename: ""
engine:
  retentionManager: SingleRetention
  tenantautoadd: true
  backupsyncmode: false
  storage:
    storageclass: SimpleFile
    properties:
      rootpath: /data/storage
  cache:
    storageclass: FastCache
    properties:
      rootpath: /cache/storage
      maxcount: 100000
      maxramusage: 1G
headermapping:
  headerprefix: x-
  retention:
  tenant: 
  apikey: 
  filename:
