port: 8000
sslport: 8443
serviceURL: https://127.0.0.1:8443
secretfile: ""
healthcheck:
  period: 30
logging:
  level: debug
  filename: ""
engine:
  retentionManager: SingleRetention
  tenantautoadd: true
  backupsyncmode: false
  storage:
    storageclass: SimpleFile
    properties:
      rootpath: H:/temp/blbstg
  backup:
    storageclass: S3Storage
    properties:
      endpoint: "http://127.0.0.1:9002"
      bucket: "goblobstore"
      accessKey: D9Q2D6JQGW1MVCC98LQL
      secretKey: LDX7QHY/IsNiA9DbdycGMuOP0M4khr0+06DKrFAr
      password: 4jsfhdjHsd?
      insecure: true
headermapping:
  headerprefix: x-
  retention: X-es-retention
  tenant: X-es-tenant
  apikey: 
  filename: X-es-filename
#  apikey: X-es-apikey
