port: 8000
sslport: 8443
serviceURL: https://127.0.0.1:8443
secretfile: "configs/secret.yaml"
apikey: false
healthcheck:
  period: 30
# enable/disable metrics 
metrics:
  enable: false
logging:
  level: info
  filename: ""
engine:
  retentionManager: SingleRetention
  tenantautoadd: true
  backupsyncmode: false
  storage:
    storageclass: S3Storage
    properties:
      endpoint: "http://127.0.0.1:9002"
      bucket: "goblobstore"
      insecure: true
      accessKey: 
      secretKey: 
      password: 
headermapping:
  headerprefix: X-
  retention: X-es-retention
  tenant: X-es-tenant
  apikey: X-es-apikey
  filename: X-es-filename

#  apikey: X-es-apikey
