port: 8000
sslport: 8443
serviceURL: https://127.0.0.1:8443
secretfile: ""
healthcheck:
  period: 30
logging:
  level: debug
  filename: ""
storage:
#  storageclass: SimpleFile
#  rootpath: H:/temp/blbstg
  storageclass: S3Storage
  endpoint: "https://127.0.0.1:9001"
  bucket: "goblobstore"
  accessKey: D9Q2D6JQGW1MVCC98LQL
  secretKey: LDX7QHY/IsNiA9DbdycGMuOP0M4khr0+06DKrFAr
  password: 4jsfhdjHsd?
  retentionManager: SingleRetention
  
headermapping:
  headerprefix: x-
  retention: X-es-retention
  tenant: X-es-tenant
  apikey: 
  filename: X-es-filename
#  apikey: X-es-apikey
